FROM python:3.8.12-slim

RUN apt-get update \
    && apt-get -y upgrade \
    && apt-get -y install --no-install-recommends curl \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

RUN pip install pip==21.3.1

RUN useradd -u 1003 -m poetry
RUN mkdir /app && chown poetry:poetry /app
USER poetry
WORKDIR /home/poetry

RUN curl -sSL https://install.python-poetry.org --output /tmp/install-poetry.py \
    && python /tmp/install-poetry.py --version 1.1.12

USER root
RUN rm -rf /tmp/*
USER poetry

COPY ./docker/install ./.scripts

WORKDIR /app

ENV PATH "/home/poetry/.local/bin:$PATH"
ENTRYPOINT ["/home/poetry/.scripts/entrypoint.sh"]
CMD ["/home/poetry/.scripts/cmd.sh"]
